# Generated by Django 2.1.4 on 2019-01-10 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dostawcy',
            fields=[
                ('id_dostawcy', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=50)),
                ('nr_telefonu', models.CharField(max_length=15)),
                ('nip', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'dostawcy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dostawy',
            fields=[
                ('id_dostawy', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
            ],
            options={
                'db_table': 'dostawy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hurtownie',
            fields=[
                ('id_hurtowni', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=64)),
                ('nip', models.CharField(max_length=10)),
                ('regon', models.CharField(max_length=9)),
                ('miejscowosc', models.CharField(max_length=30)),
                ('ulica', models.CharField(blank=True, max_length=40, null=True)),
                ('nr_budynku', models.CharField(max_length=4)),
                ('nr_lokalu', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'hurtownie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Magazyny',
            fields=[
                ('id_magazynu', models.BigIntegerField(primary_key=True, serialize=False)),
                ('miejscowosc', models.CharField(max_length=30)),
                ('ulica', models.CharField(blank=True, max_length=40, null=True)),
                ('nr_budynku', models.CharField(max_length=4)),
                ('nr_lokalu', models.CharField(blank=True, max_length=4, null=True)),
                ('powierzchnia', models.FloatField()),
            ],
            options={
                'db_table': 'magazyny',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pamiec',
            fields=[
                ('id_pamieci', models.BigIntegerField(primary_key=True, serialize=False)),
                ('typ', models.CharField(max_length=4)),
                ('pojemnosc', models.BigIntegerField()),
                ('id_towaru', models.BigIntegerField()),
            ],
            options={
                'db_table': 'pamiec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlytaGlowna',
            fields=[
                ('id_plyty_glownej', models.BigIntegerField(primary_key=True, serialize=False)),
                ('chipset', models.CharField(max_length=15)),
                ('standard_pamieci', models.CharField(max_length=4)),
                ('id_towaru', models.BigIntegerField()),
            ],
            options={
                'db_table': 'plyta_glowna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Poczta',
            fields=[
                ('id_poczty', models.BigIntegerField(primary_key=True, serialize=False)),
                ('miasto', models.CharField(max_length=30)),
                ('kod_pocztowy', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'poczta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Procesor',
            fields=[
                ('id_procesora', models.BigIntegerField(primary_key=True, serialize=False)),
                ('liczba_rdzeni', models.BigIntegerField()),
                ('taktowanie', models.FloatField()),
                ('id_towaru', models.BigIntegerField()),
            ],
            options={
                'db_table': 'procesor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Przewoznicy',
            fields=[
                ('id_przewoznika', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=50)),
                ('nr_telefonu', models.CharField(max_length=15)),
                ('id_hurtowni', models.BigIntegerField()),
            ],
            options={
                'db_table': 'przewoznicy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PunktySprzedazy',
            fields=[
                ('id_punktu_sprzedazy', models.BigIntegerField(primary_key=True, serialize=False)),
                ('miejscowosc', models.CharField(max_length=30)),
                ('ulica', models.CharField(blank=True, max_length=40, null=True)),
                ('nr_budynku', models.CharField(max_length=4)),
                ('nr_lokalu', models.CharField(blank=True, max_length=4, null=True)),
                ('powierzchnia', models.FloatField()),
            ],
            options={
                'db_table': 'punkty_sprzedazy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SzczegolyZamowienia',
            fields=[
                ('id_zmowienia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ilosc', models.BigIntegerField()),
            ],
            options={
                'db_table': 'szczegoly_zamowienia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Towary',
            fields=[
                ('id_towaru', models.BigIntegerField(primary_key=True, serialize=False)),
                ('produent', models.CharField(max_length=60)),
                ('kod_producenta', models.CharField(max_length=20)),
                ('model', models.CharField(blank=True, max_length=20, null=True)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'towary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wlasciciele',
            fields=[
                ('id_wlasciciela', models.BigIntegerField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=40)),
                ('data_od', models.DateField()),
                ('data_do', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wlasciciele',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wynagrodzenia',
            fields=[
                ('id_wynagrodzenia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('premia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_pracownika', models.BigIntegerField()),
            ],
            options={
                'db_table': 'wynagrodzenia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zamwienia',
            fields=[
                ('id_zmowienia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('id_klienta', models.BigIntegerField()),
            ],
            options={
                'db_table': 'zamówienia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SzczegolyDostawy',
            fields=[
                ('id_dostawy', models.ForeignKey(db_column='id_dostawy', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='shop.Dostawy')),
                ('id_towaru', models.BigIntegerField()),
                ('ilosc', models.BigIntegerField()),
            ],
            options={
                'db_table': 'szczegoly_dostawy',
                'managed': False,
            },
        ),
    ]
